---

- name: Add users (serv + data + viz)
  hosts: serv, data, viz
  vars:
    staff:
      - { name: amm, uid: 1001 }
      - { name: nse, uid: 1002 }
      - { name: mgn, uid: 1003 }
      - { name: msm, uid: 1004 }
      - { name: amr, uid: 1005 }
  tasks:

    - name: Add users
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ staff }}"
